config/routes.rb
Rails.application.routes.draw do
 
  get 'userparams/new'
  get 'userparams/edit'
  get 'userparams/show'
  devise_for :users
  root 'posts#index'
  resources :posts
  resources :userparams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true
	  mount_uploaders :songs, MusicUploader
  serialize :songs, JSON # If you use SQLite, add this line.

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_one :userparam
end

app/models/userparam.rb
class Userparam < ApplicationRecord
    belongs_to :user
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50" }, default_url: "/assets/avatar.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
    validates :age, numericality: { only_integer: true }
    #validates_inclusion_of :age, :in => 18..45
    validates :firstname, :lastname, :age , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :authenticate_user!
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  	user_root GET    /persons/profile(.:format)  persons#profile
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, {songs: []})
    end
end

app/controllers/userparams_controller.rb
class UserparamsController < ApplicationController
  before_action :authenticate_user!

  def new
    @userparam = Userparam.new
  end

  def create
    @userparam = current_user.build_userparam(profile_params)
    if @userparam.save
      redirect_to userparam_path(@userparam.id)
    else render 'new'
    end

  end

  def show
  end

  def edit
    @userparam = current_user.userparam
  end

  def update
    @userparam = Userparam.find_by(user_id: current_user.id)
    if @userparam.update(profile_params)
       redirect_to userparam_path(@userparam.id)
    else render 'edit'
    end

  end

private

  def profile_params
    params.require(:userparam).permit(:user_id, :firstname, :lastname, :age, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if user_signed_in? %>
   <% if current_user.userparam.nil? %>
  <%= link_to "Профіль", new_userparam_path%>
<% else %>
  <%= link_to userparam_path(current_user.id) do%>
    <%= current_user.email.split('@').first %>'s profile
  <%end%>
<%end%>
  <%= link_to "Home", root_path %> |
   <%= link_to "Add new post(MUSIC)",  new_post_path %>|
  <%= link_to "Logout",  destroy_user_session_path, method: :delete %>
<% else %>
   <%= link_to "Login", new_user_session_path %>
<% end %>



  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <%= form.file_field :songs, multiple: true %><br><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.user.email %> </td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Email:</strong>
  <%= @post.user.email %>
</p>
<% @post.songs.each do |music| %><br>
<audio controls>
  
  <source src="<%= music.url %>" type="audio/mpeg">
  Your browser does not support the audio tag.
</audio>

<% end %>
<br>

<%= link_to 'Back', :back %>
<% if user_signed_in? && @post.user_id == current_user.id %>
<%= link_to 'Edit', edit_post_path(@post) %> |

<%= link_to "delete", post_path(@post.id), method: :delete %><br /></p>
<% end %>

app/views/userparams/_form.html.erb
<% if @userparam.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@userparam.errors.count, "error") %> prohibited this userparam from being saved:</h2>
 
    <ul>
    <% @userparam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.file_field :avatar %><br>
Ім'я:
<%= f.text_field :firstname %><br>
Прізвище:
<%= f.text_field :lastname %><br>
Вік:
<%= f.text_field :age %><br>

app/views/userparams/edit.html.erb
<h3>Профіль користувача
  <b><%=@userparam.user.email.split('@').first%></b>
</h3>
<%=form_for @userparam, url:userparam_path(current_user.id) do |f|%>
<%=render 'userparams/form', f:f%>
<%=f.submit "Оновити"%>
<%end%>

app/views/userparams/new.html.erb
<%= form_for @userparam, url: userparams_path do |f| %>
    <%=render 'userparams/form', f:f%>
    <%= f.submit "Створити" %>
    <% end %>  

app/views/userparams/show.html.erb
<br>
<h3>Профіль користувача: 
<%= image_tag current_user.userparam.avatar.url(:thumb) %><br /><br>
<b><%=current_user.email.split('@').first%></b></h3><br>
<br />
<br />
<h5>  
Ім'я:  <%=current_user.userparam.firstname%>
</h5>

<h5>
Прізвище:  <%=current_user.userparam.lastname%>
</h5>
<h5>
Вік:   <%=current_user.userparam.age %>
</h5>
<%if user_signed_in? && current_user.id == current_user.id%>

<%=link_to "Редагувати профіль", edit_userparam_path(current_user.id)%><br>  
<%end%>